"""empty message

Revision ID: 142ead1ea77b
Revises: 4b8de42a760b
Create Date: 2024-02-21 21:30:16.195973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142ead1ea77b'
down_revision = '4b8de42a760b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('education_qualification', sa.String(length=50), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('subjects', sa.String(length=200), nullable=True),
    sa.Column('past_experience', sa.Boolean(), nullable=True),
    sa.Column('experience_years', sa.String(length=20), nullable=True),
    sa.Column('experience_description', sa.Text(), nullable=True),
    sa.Column('interest_join', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('teaching_mode', sa.String(length=50), nullable=True),
    sa.Column('student_level', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confirmation_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutor')
    # ### end Alembic commands ###
