"""empty message

Revision ID: 4b8de42a760b
Revises: 82b9d52bb9fd
Create Date: 2024-02-19 17:14:58.724120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8de42a760b'
down_revision = '82b9d52bb9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'paid')
    # ### end Alembic commands ###
