"""empty message

Revision ID: 652a1ce03174
Revises: b49f03f81e6a
Create Date: 2024-03-10 12:46:17.799329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652a1ce03174'
down_revision = 'b49f03f81e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorfeepayment', sa.Column('paystack_tutorfeepayment_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorfeepayment', 'paystack_tutorfeepayment_id')
    # ### end Alembic commands ###
