"""empty message

Revision ID: 82b9d52bb9fd
Revises: beb538e77146
Create Date: 2024-02-18 16:51:13.261187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b9d52bb9fd'
down_revision = 'beb538e77146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('paystack_subscription_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'paystack_subscription_id')
    # ### end Alembic commands ###
