"""empty message

Revision ID: d971a74e15b9
Revises: 3095d43c54fb
Create Date: 2024-03-29 15:34:55.188698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd971a74e15b9'
down_revision = '3095d43c54fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorfeepayment', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorfeepayment', 'paid')
    # ### end Alembic commands ###
